### ISSUE TITLE
Draw message is shown twice after the Game ends in Draw 

### ISSUE THREAD

**Issue by voxer03** [voxer03/Tic-Tac-Toe#1]
If needed any help in understanding code  feel free to contact

**Comment by TusharSharmaIN** [comment]
Please assign this to me. I want to do this.

**Comment by voxer03** [comment]
Assigned to you @TusharSharmaIN  Happy coding

**Comment by TusharSharmaIN** [comment]
please add label hactoberfest it will be helpful.
